#!/bin/sh

# ##############################################################################
# #                                  ENV VARS                                  # 
# ##############################################################################

# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }
start() { pkill -x "$1"; { sleep 0.1; "$@" & }; }
monitor() { bspc monitor "$@" & }

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

monitor -d 1 2 3 4 5 6 7 8 9  

rule firefox desktop=1
rule discord desktop=2 focus=off 
rule Spotify desktop=3
rule Code desktop=5

rule "SkyClient (Forge 1.8.9)" desktop=4
rule PolyMC desktop=6
rule "Minecraft 1.12.2" desktop=4
rule "Minecraft 1.8.9" desktop=4
rule "Minecraft* 1.18.2" desktop=6
rule Steam desktop=6

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

config border_width		1.5
config window_gap		0
config split_ratio		0.52
config borderless_monocle	true
config gapless_monocle		true
config focus_follows_pointer 	true
config external_rules_command 	"$HOME/.config/bspwm/scripts/spotify.sh"

# ##############################################################################
# #                                 MISCELLANEOUS                              #
# ##############################################################################

config normal_border_color 	"#707880"
config active_border_color 	"#A994DF"
config focused_border_color 	"#A994DF"
config presel_feedback_color 	"#b24744"

# ##############################################################################
# #                                 STARTUP                                    #
# ##############################################################################

# polybar
exec ~/.config/polybar/launch.sh & 

# picom
exec picom --experimental-backends &

# mouse settings
xsetroot -cursor_name left_ptr &
xset m 0 0
xinput set-prop 8 293 -0.77

# display
xset -dpms s off

# wallpaper
~/.fehbg &

# sxhkd
start sxhkd 
